# register
POST /api/register
Host: localhost
Content-Type: application/json

{
    "name": "kazuo",
    "email": "aa@a",
    "password": "11111111"
}


###
# login
POST /api/login
Host: localhost
Content-Type: application/json

{
    "email": "aa@a",
    "password": "11111111"
}

###

# show
GET /api/songs/43
Host: localhost
Content-Type: application/json

###


# store
POST /api/songs
Host: localhost
Content-Type: application/json
Authorization: Bearer 2|PvO22eNPQLgG8oKZKhJYmJ58B7QJFhJiMx5rdCIO

{
    "category_id": "2",
    "title": "title",
    "file_name": "2.mp3",
    "description": "aaaa",
    "image": "2.jpeg"
}


###

# update
PUT  /api/songs/1
Host: localhost
Content-Type: application/json
Authorization: Bearer 2|PvO22eNPQLgG8oKZKhJYmJ58B7QJFhJiMx5rdCIO

{
    "category_id": "2",
    "title": "title",
    "file_name": "2.mp3",
    "description": "aaaa",
    "image": "2.jpeg"
}
