# register
POST /api/register
Host: localhost
Content-Type: application/json

{
    "name": "kazuo",
    "email": "aa@a",
    "password": "11111111"
}

###
# login
POST /api/login
Host: localhost
Content-Type: application/json

{
    "email": "aa@a",
    "password": "11111111"
}

###

# songshow
GET /api/songs/15
Authorization: Bearer 
Host: localhost
Content-Type: application/json


###

#artistshow
GET /api/artists/15
Authorization: Bearer 9|oruKsDrVdEhNmm2ZrrOV7vBBRBLmwhNMVFAAv94s
Host: localhost
Content-Type: application/json


# # store
# POST /api/songs
# Host: localhost
# Content-Type: application/json
# Authorization: Bearer 2|PvO22eNPQLgG8oKZKhJYmJ58B7QJFhJiMx5rdCIO

# {
#     "category_id": "2",
#     "title": "title",
#     "file_name": "2.mp3",
#     "description": "aaaa",
#     "image": "2.jpeg"
# }


# ###

# # update
# PUT  /api/songs/48
# Host: localhost
# Content-Type: application/json
# Authorization: Bearer 2|PvO22eNPQLgG8oKZKhJYmJ58B7QJFhJiMx5rdCIO

# {
#     "category_id": "2",
#     "title": "titleeeen",
#     "file_name": "2.mp3",
#     "description": "bbbb",
#     "image": "2.jpeg"
# }

###

# likestore
POST /api/songs/6/likes
Host: localhost
Content-Type: application/json
Authorization: Bearer 7|R6qvlNBfyNUmCd8e4GkHAIEUAUBxwH8YJOsB9VA8

{
    "user_id": "15",
    "song_id": "16"
}

###

# likedestroy
DELETE /api/songs/11/likes/91
Host: localhost
Content-Type: application/json
Authorization: Bearer 8|usOuMgoNVFoVIDDPeneCNlCc3GLIUP4peNfnQaBE

###

# followstore
POST /api/artists/1/follows
Host: localhost
Content-Type: application/json
Authorization: Bearer 9|oruKsDrVdEhNmm2ZrrOV7vBBRBLmwhNMVFAAv94s

{
    "user_id": "7",
    "artist_id": "7"
}

###

# followdestroy
DELETE /api/artists/7/follows/29
Host: localhost
Content-Type: application/json
Authorization: Bearer 9|oruKsDrVdEhNmm2ZrrOV7vBBRBLmwhNMVFAAv94s
