# register
POST /api/register
Host: localhost
Content-Type: application/json

{
    "name": "kazuo",
    "email": "aa@a",
    "password": "11111111"
}

###
# login
POST /api/login
Host: localhost
Content-Type: application/json

{
    "email": "1@1",
    "password": "11111111"
}

###

# songshow
GET /api/songs/33
Authorization: Bearer 5|7obE2c3v6fBra7SFFSd0iBnWh2io4Ngv3sQJSMIW
Host: localhost
Content-Type: application/json


###

#artistshow
GET /api/artists/8
Authorization: Bearer 5|7obE2c3v6fBra7SFFSd0iBnWh2io4Ngv3sQJSMIW
Host: localhost
Content-Type: application/json


# # store
# POST /api/songs
# Host: localhost
# Content-Type: application/json
# Authorization: Bearer 2|PvO22eNPQLgG8oKZKhJYmJ58B7QJFhJiMx5rdCIO

# {
#     "category_id": "2",
#     "title": "title",
#     "file_name": "2.mp3",
#     "description": "aaaa",
#     "image": "2.jpeg"
# }


# ###

# # update
# PUT  /api/songs/48
# Host: localhost
# Content-Type: application/json
# Authorization: Bearer 2|PvO22eNPQLgG8oKZKhJYmJ58B7QJFhJiMx5rdCIO

# {
#     "category_id": "2",
#     "title": "titleeeen",
#     "file_name": "2.mp3",
#     "description": "bbbb",
#     "image": "2.jpeg"
# }

###

# likestore
POST /api/songs/1/likes
Host: localhost
Content-Type: application/json
Authorization: Bearer 2|emhEeFh2oPaKocFcDUyxPuMA5J5O8py5CCLiJDD7

{
    "user_id": "1",
    "song_id": "1"
}

###

# likedestroy
DELETE /api/songs/11/likes/91
Host: localhost
Content-Type: application/json
Authorization: Bearer 8|usOuMgoNVFoVIDDPeneCNlCc3GLIUP4peNfnQaBE

###

# followstore
POST /api/artists/1/follows
Host: localhost
Content-Type: application/json
Authorization: Bearer 9|oruKsDrVdEhNmm2ZrrOV7vBBRBLmwhNMVFAAv94s

{
    "user_id": "7",
    "artist_id": "7"
}

###

# followdestroy
DELETE /api/artists/7/follows/29
Host: localhost
Content-Type: application/json
Authorization: Bearer 9|oruKsDrVdEhNmm2ZrrOV7vBBRBLmwhNMVFAAv94s
